version: "3.3"
services:
  nginx-prod:
    image: nginx:stable-alpine
    restart: unless-stopped
    container_name: web-prod
    hostname: web-prod
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - mysql-prod
      - redis-prod
      - service-prod
    links:
      - service-prod
    ports:
      - 80:80
    volumes:
      - ./html/web:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx:rw
  mysql-prod:
    image: mysql:8.0
    restart: unless-stopped
    container_name: mysql-prod
    hostname: mysql-prod
    command: --default-authentication-plugin=mysql_native_password --default-time_zone='+8:00'
    ports:
      - 3307:3306
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=hksqlpwd
      - MYSQL_DATABASE=bookkeeping
      - MYSQL_USER=bk
      - MYSQL_PASSWORD=hksqlpwd
    volumes:
      - ./mysql/data:/var/lib/mysql:rw
      - ./mysql/init:/docker-entrypoint-initdb.d/
      - ./logs/mysql:/var/log/mysql:rw
  redis-prod:
    image: redis:6-alpine
    restart: unless-stopped
    container_name: redis-prod
    hostname: redis-prod
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 6378:6379
    volumes:
      # 配置文件如果开启守护模式 会导致无效重启 其他配置会导致无法远程连接(没有查明问题)
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./logs/redis:/data/logs
      - ./redis/data:/data/db/
  service-prod:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: service-prod
    hostname: service-prod
    working_dir: /root/app
    depends_on:
      - mysql-prod
      - redis-prod
    links:
      - mysql-prod
      - redis-prod
    env_file:
      - docker.env
    environment:
      - NODE_ENV=production
      - server_post=8990
      - TZ=Asia/Shanghai
    ports:
      - 8990:8990
    command: pm2-runtime ./processes.json
    # command: node ./dist/setup.js
    # command: yarn dev
    volumes:
      - ./server:/root/app
      - ./server/node_modules:/root/app/node_modules
      - ./logs/server:/root/app/logs
      - ./logs/server/ormlogs.log:/root/app/ormlogs.log
